name: Serge's World
description: Blogging about software development, astronomy, genealogy and more
meta_description: "Serge's World, Blogging about software development astronomy genealogy and more"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
excerpt_separator: <!--more-->
baseurl: /
domain_name: 'http://sjmeunier.github.io'
google_analytics: 'UA-84278851-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://sjmeunier.github.io'
author:         'Serge Meunier'

collections:
  my_tags:
    output: true
    permalink: /tag/:name/

defaults:
  -
     scope:
       path: ""
       type: my_tags
     values:
       layout: tag_list